name: 'Setup PHP for PocketMine-MP'
description: 'Build and install PHP for PocketMine-MP and related projects'
author: 'pmmp'
inputs:
  php-version:
    required: true
    description: 'PHP version to build and install'
  install-path:
    required: true
    description: 'Path to install the binary to'

runs:
  using: 'node12'
  main: 'dist/index.js'
