name: 'Setup PHP for PocketMine-MP'
description: 'Build and install PHP for PocketMine-MP and related projects'
author: 'pmmp'
inputs:
  php-version:
    required: true
    description: 'PHP version to build and install'
  install-path:
    required: true
    description: 'Path to install the binary to'
  pm-version-major:
    required: false
    description: 'Major version of PocketMine-MP to compile extensions for'
    default: 4

runs:
  using: 'node16'
  main: 'dist/index.js'
